# docker-compose.production.yml
version: '3.8' # Use version 3.8 for compatibility with most Docker setups

services:
  web:
    build: .
    ports:
      - "80:5000"
    environment:
      - DATABASE_URL=postgresql://handoff:${DB_PASSWORD}@db:5432/handoffhub
      - SECRET_KEY=f4b28f9e64b13709d7f6b3b79cf6a4a79c6ff27d01fcbf628aa0b47b93bcd8e1
      - FLASK_ENV=production
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_USERNAME=linuspiorkowsky@gmail.com
      - MAIL_PASSWORD=Natasha78
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    restart: always
    command: gunicorn app:app --bind 0.0.0.0:5000 --workers 4 --threads 2

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=handoff
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=handoffhub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  redis_data:
