# docker-compose.production.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:uzCcUGoDsrJatKRDEQueNLdIhSpIElzT@gondola.proxy.rlwy.net:47326/railway
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=production
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    restart: always
    command: gunicorn app:app --bind 0.0.0.0:5000 --workers 4 --threads 2

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=handoff
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=handoffhub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  redis_data:
